"""
Tool 5: Edit
=============
Lets Claude make surgical changes to an existing file.
Only the matched text is replaced — everything else stays.

IMPORTANT:
  - Claude MUST read the file first before editing
  - old_string must be an EXACT match (including whitespace/indentation)
  - If old_string appears multiple times → Claude uses more context to make it unique
  - Use Write (Tool 4) if you want to replace the entire file
"""

import asyncio
import os
from dotenv import load_dotenv
from claude_agent_sdk import query, ClaudeAgentOptions, ResultMessage, AssistantMessage, ToolUseBlock, TextBlock

load_dotenv()

options = ClaudeAgentOptions(
    model="sonnet",
    env={"ANTHROPIC_API_KEY": os.getenv("ANTHROPIC_API_KEY")},
    # Read → understand the file before editing
    # Edit → make the targeted fix
    allowed_tools=["Read", "Edit", "Glob","Grep"],
    permission_mode="bypassPermissions",
    max_turns=5,
)


async def main():
    print("=== Tool: Edit ===\n")

    # Show the file BEFORE editing
    print("--- BEFORE ---")
    with open("sample_data/utils.py") as f:
        for i, line in enumerate(f, 1):
            print(f"{i:3} {line}", end="")
    print("\n")

    async for message in query(
        prompt="""
        Find report file and add a report generated by Claude
        """,
        options=options,
    ):
        if isinstance(message, AssistantMessage):
            for block in message.content:
                if isinstance(block, ToolUseBlock):
                    if block.name == "Edit":
                        print(f"[Claude called] Edit(")
                        print(f"  file  : {block.input.get('file_path')}")
                        print(f"  old   : {repr(block.input.get('old_string'))}")
                        print(f"  new   : {repr(block.input.get('new_string'))}")
                        print(f")")
                    else:
                        print(f"[Claude called] {block.name}({block.input})")
                elif isinstance(block, TextBlock):
                    print(f"[Claude says] {block.text}")

        elif isinstance(message, ResultMessage):
            print(f"\n[Cost: ${message.total_cost_usd:.4f} | Turns: {message.num_turns}]")

    # Show the file AFTER editing
    print("\n--- AFTER ---")
    with open("sample_data/utils.py") as f:
        for i, line in enumerate(f, 1):
            print(f"{i:3} {line}", end="")


asyncio.run(main())
